#!/bin/sh

# Time-stamp: <2013-06-09 11:20:44 Sunday by lzy>

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# language settings
#export LANG=zh_CN.UTF-8
export LC_CTYPE=zh_CN.UTF-8

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

# input settings
if [ -x /usr/bin/scim ] || [ -x /usr/local/bin/scim ]; then
    export XMODIFIERS="@im=SCIM"
    export XIM=SCIM
    export XIM_PROGRAM=scim
    export GTK_IM_MODULE=scim
    export QT_IM_MODULE=scim
    scim -d
fi

# set the cursor
xsetroot -cursor_name left_ptr
# start xmonad
exec ck-launch-session dbus-launch xmonad.start
